/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mahadevfoam_dealers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import sun.security.rsa.RSACore;

/**
 *
 * @author Mahadav
 */
public class bills extends javax.swing.JFrame {
    private Object jspinner4;

    /**
     * Creates new form bills
     */
    public bills() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jcusnamebill2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jinvoicenumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcusname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcomboproductselect = new javax.swing.JComboBox();
        jcombocompanyselect = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfrate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlbtotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtfdis = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jlbdis = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jtflength = new javax.swing.JTextField();
        jtfwidth = new javax.swing.JTextField();
        jtfheight = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jRbretails = new javax.swing.JRadioButton();
        jrbwholesale = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        Jinvoicenumberbill = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jcusnamebill = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jcusaddress = new javax.swing.JTextField();
        Jinvoicedate = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jcusphone = new javax.swing.JTextField();
        Jcusidbill = new javax.swing.JTextField();

        jcusnamebill2.setEditable(false);
        jcusnamebill2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcusnamebill2FocusGained(evt);
            }
        });
        jcusnamebill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcusnamebill2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("Invoice Id:-");

        Jinvoicenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JinvoicenumberFocusGained(evt);
            }
        });
        Jinvoicenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JinvoicenumberActionPerformed(evt);
            }
        });

        jLabel3.setText("Customer/dealer Id:-");

        jButton1.setText("Open customer portal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Customer Name:-");

        jcusname.setEditable(false);
        jcusname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcusnameFocusGained(evt);
            }
        });
        jcusname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcusnameActionPerformed(evt);
            }
        });

        jLabel5.setText("Select Product:-");

        jcomboproductselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcomboproductselect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcomboproductselectFocusGained(evt);
            }
        });

        jcombocompanyselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcombocompanyselect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcombocompanyselectFocusGained(evt);
            }
        });

        jLabel6.setText("Select company:-");

        jLabel7.setText("Select Size:-");

        jLabel8.setText("Length in inches");

        jLabel9.setText("Width in inches");

        jLabel10.setText("Height in MM");

        jLabel11.setText("Rate:-");

        jtfrate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfrateFocusGained(evt);
            }
        });

        jLabel12.setText("Quantity:-");

        jLabel13.setText("total:-");

        jlbtotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setText("Discount (%):-");

        jtfdis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfdisFocusLost(evt);
            }
        });

        jLabel16.setText("NET AMOUNT:-");

        jlbdis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbdis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jlbdisFocusGained(evt);
            }
        });

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DELETE");

        jButton5.setText("VIEW");

        jButton6.setText("GENERATE BILL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(987903480000L), new java.util.Date(987903480000L), new java.util.Date(2029282680000L), java.util.Calendar.MONTH));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        buttonGroup1.add(jRbretails);
        jRbretails.setText("RETAIL");

        buttonGroup1.add(jrbwholesale);
        jrbwholesale.setText("WHOLESALE");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comp_Name", "Product_name", "Length", "Width", "Height (in mm)", "Rate", "Quantity", "Total", "Discount %", "Net Amount"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel14.setText("Invoice Id:-");

        jLabel17.setText("Invoice Date:-");

        jLabel18.setText("Customer Id:-");

        jLabel19.setText("Customer Name:-");

        jcusnamebill.setEditable(false);
        jcusnamebill.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcusnamebillFocusGained(evt);
            }
        });
        jcusnamebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcusnamebillActionPerformed(evt);
            }
        });

        jLabel20.setText("Customer Address:-");

        jcusaddress.setEditable(false);
        jcusaddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcusaddressFocusGained(evt);
            }
        });
        jcusaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcusaddressActionPerformed(evt);
            }
        });

        Jinvoicedate.setEditable(false);
        Jinvoicedate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JinvoicedateFocusGained(evt);
            }
        });
        Jinvoicedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JinvoicedateActionPerformed(evt);
            }
        });

        jLabel21.setText("Customer Phone:-");

        jcusphone.setEditable(false);
        jcusphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcusphoneFocusGained(evt);
            }
        });
        jcusphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcusphoneActionPerformed(evt);
            }
        });

        Jcusidbill.setEditable(false);
        Jcusidbill.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JcusidbillFocusGained(evt);
            }
        });
        Jcusidbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcusidbillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JTFID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addComponent(jcombocompanyselect, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcomboproductselect, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfrate, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcusname, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfdis, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbdis, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtflength, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfwidth, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfheight, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Jinvoicenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(108, 108, 108)
                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbretails)
                            .addComponent(jrbwholesale)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcusnamebill, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcusaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jcusidbill, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Jinvoicenumberbill, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jinvoicedate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jcusphone, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jinvoicenumberbill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jcusidbill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jinvoicedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jcusnamebill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jcusaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jcusphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRbretails)
                                        .addGap(5, 5, 5)
                                        .addComponent(jrbwholesale)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Jinvoicenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(JTFID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(jcomboproductselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jcombocompanyselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jcusname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtflength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfwidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfrate)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(jlbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfdis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlbdis, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)
                                    .addComponent(jButton5)
                                    .addComponent(jButton7)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new customer_management().setVisible(true);
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcusnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcusnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusnameActionPerformed

    private void jcusnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcusnameFocusGained
        try {
             Class.forName("java.sql.Driver");
                    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
                    Statement stmt=conn.createStatement();
                    int id=Integer.parseInt(JTFID.getText());
                    String sql="select cus_name from customer_details WHERE cus_id='"+id+"';";
                    ResultSet rs1=stmt.executeQuery(sql);
                    
                    if(rs1.next())
                    {
                      jcusname.setText(rs1.getString("cus_name"));
                    }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jcusnameFocusGained

    private void jcombocompanyselectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcombocompanyselectFocusGained
          try {
        Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        String combo_group = "Select DISTINCT cname from company_list";
        ResultSet rs = stmt.executeQuery(combo_group);

        jcombocompanyselect.removeAllItems();
        while(rs.next())
        {
            jcombocompanyselect.addItem(rs.getString("cname"));
        }
        
            } 
        catch (Exception e)
            {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_jcombocompanyselectFocusGained

    private void jcomboproductselectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcomboproductselectFocusGained
        try {
        Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        String company=jcombocompanyselect.getSelectedItem().toString();
        String companyid= "select cid from COMPANY_LIST where cname='"+company+"';";
        ResultSet rs=stmt.executeQuery(companyid);
        if(rs.next())
        {
            String c_id=rs.getString("cid");
            String PRODUCTLIST = "Select pname from product where cid='"+c_id+"';";
            ResultSet rs1 = stmt.executeQuery(PRODUCTLIST);
        jcomboproductselect.removeAllItems();
        while(rs1.next())
        {
            jcomboproductselect.addItem(rs1.getString("Pname"));
        }    
        }
            } 
        catch (Exception e)
            {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_jcomboproductselectFocusGained

    private void jtfrateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfrateFocusGained
                try 
        {
        Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        
        int length=Integer.parseInt(jtflength.getText());
        int width=Integer.parseInt(jtfwidth.getText());
        int height=Integer.parseInt(jtfheight.getText());
        long sq_inches_per_mm=length*width*height;
        
        String product=jcomboproductselect.getSelectedItem().toString();
        String price_from_db="select price_72_36 from product where pname='"+product+"';";
        ResultSet rs=stmt.executeQuery(price_from_db);
        
        if(rs.next())
        {
           int price=rs.getInt("price_72_36");
           long rate=(sq_inches_per_mm*price)/259200;
           jtfrate.setText(rate+"");
        }
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jtfrateFocusGained

    private void jlbdisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlbdisFocusGained
       
       
    }//GEN-LAST:event_jlbdisFocusGained

    private void jtfdisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfdisFocusLost
       int discount=Integer.parseInt(jtfdis.getText().trim());
       int amt=Integer.parseInt(jlbtotal.getText());
       int disamt=(discount*amt)/100;
       int netamt=amt-disamt;
       jlbdis.setText(netamt+"");
    }//GEN-LAST:event_jtfdisFocusLost

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        //Spinner
        //Model property

        //jLabel1.setText(new SimpleDateFormat("yyyy-MM-dd").format(jSpinner1.getValue()));
        String date=(new SimpleDateFormat("yyyy-MM-dd").format(jSpinner1.getValue()));
       // jcusname.setText(date); the value is stored in variable can be directly into database.

    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        try
        {
          Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement();
              
          String date=(new SimpleDateFormat("yyyy-MM-dd").format(jSpinner1.getValue()));
          int invoice_id=Integer.parseInt(Jinvoicenumber.getText());
          int cus_deal_id=Integer.parseInt(JTFID.getText());
          String cus_name=jcusname.getText();
          String company=jcombocompanyselect.getSelectedItem().toString();
          String product=jcomboproductselect.getSelectedItem().toString();
          int length=Integer.parseInt(jtflength.getText());
          int width=Integer.parseInt(jtfwidth.getText());
          int height=Integer.parseInt(jtfheight.getText());
          int rate=Integer.parseInt(jtfrate.getText());
          int quantity=(Integer)jSpinner5.getValue();
          int total=Integer.parseInt(jlbtotal.getText());
          int discount=Integer.parseInt(jtfdis.getText());
          int netamt=Integer.parseInt(jlbdis.getText());
          
          
          if(jRbretails.isSelected())
          {
          String sqlinsertreatils="insert into bills_retails values('"+date+"','"+invoice_id+"','"+cus_deal_id+"','"+cus_name+"','"+company+"','"+product+"','"+length+"','"+width+"','"+height+"','"+rate+"','"+quantity+"','"+total+"','"+discount+"','"+netamt+"')";
          stmt.executeUpdate(sqlinsertreatils);
          
           JOptionPane.showMessageDialog(this, "Bill saved.");
          
          jcusname.setText(null);
          jcombocompanyselect.setSelectedIndex(0);
          jcomboproductselect.setSelectedIndex(0);
          jtflength.setText(null);
          jtfwidth.setText(null);
          jtfheight.setText(null);
          jtfrate.setText(null);
          jlbtotal.setText(null);
          jtfdis.setText(null);
          jlbdis.setText(null);
          
          new quick_task_update().setVisible(true);
          
          int val=0;
          jSpinner5.setValue(Integer.valueOf(val));
          
          }
          if(jrbwholesale.isSelected())
          {
           String sqlinsertwholesale="insert into bills_wholesale values('"+date+"','"+invoice_id+"','"+cus_deal_id+"','"+cus_name+"','"+company+"','"+product+"','"+length+"','"+width+"','"+height+"','"+rate+"','"+quantity+"','"+total+"','"+discount+"','"+netamt+"')";   
          stmt.executeUpdate(sqlinsertwholesale);
          
           JOptionPane.showMessageDialog(this, "Bill saved.");
          
          jcusname.setText(null);
          jcombocompanyselect.setSelectedIndex(0);
          jcomboproductselect.setSelectedIndex(0);
          jtflength.setText(null);
          jtfwidth.setText(null);
          jtfheight.setText(null);
          jtfrate.setText(null);
          jlbtotal.setText(null);
          jtfdis.setText(null);
          jlbdis.setText(null);
          
          
          new quick_task_update().setVisible(true);
          }
          
          else
          {
              JOptionPane.showMessageDialog(this, "pls. select category");
          }
          
         
          
        }
        
        
        
        catch (Exception e) 
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JinvoicenumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JinvoicenumberFocusGained
        try 
        {
          Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement();
            
         if(jRbretails.isSelected()){
         String sqlinvoiceid="select ifnull(max(invoice_id),'0') from bills_retails;";
         ResultSet rs=stmt.executeQuery(sqlinvoiceid);
         if(rs.next()){
         String invoiceid=rs.getString("ifnull(max(invoice_id),'0')");
         int maxinvoiceid=Integer.parseInt(invoiceid);
         int newinvoiceid=maxinvoiceid+1;
         Jinvoicenumber.setText(""+newinvoiceid);
         }}
         
         
         if (jrbwholesale.isSelected()) {
         String sqlinvoiceid="select ifnull(max(invoice_id),'0') from bills_wholesale;";
         ResultSet rs=stmt.executeQuery(sqlinvoiceid);
         if(rs.next()){
         String invoiceid=rs.getString("ifnull(max(invoice_id),'0')");
         int maxinvoiceid=Integer.parseInt(invoiceid);
         int newinvoiceid=maxinvoiceid+1;
         Jinvoicenumber.setText(""+newinvoiceid);
         }}
         
        } 
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, e.getMessage());
        }
          
    }//GEN-LAST:event_JinvoicenumberFocusGained

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       new office_management_menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void JinvoicenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JinvoicenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JinvoicenumberActionPerformed

    private void jcusnamebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcusnamebillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusnamebillActionPerformed

    private void jcusnamebillFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcusnamebillFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusnamebillFocusGained

    private void jcusaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcusaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusaddressActionPerformed

    private void jcusaddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcusaddressFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusaddressFocusGained

    private void jcusnamebill2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcusnamebill2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusnamebill2FocusGained

    private void jcusnamebill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcusnamebill2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusnamebill2ActionPerformed

    private void JinvoicedateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JinvoicedateFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_JinvoicedateFocusGained

    private void JinvoicedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JinvoicedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JinvoicedateActionPerformed

    private void jcusphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcusphoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusphoneFocusGained

    private void jcusphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcusphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcusphoneActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try 
        {
          Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement();
          
          int invoice_id=Integer.parseInt(Jinvoicenumberbill.getText());
          String sql="SELECT b.cus_id,b.cus_name,cus_address,cus_phone FROM bills_retails b, customer_details c WHERE b.cus_id=c.cus_id && invoice_id="+invoice_id+";";
          ResultSet rs=stmt.executeQuery(sql);
                if(rs.next()){
                Jcusidbill.setText(rs.getString("cus_id"));    
                jcusnamebill.setText(rs.getString("cus_name"));
                jcusaddress.setText(rs.getString("cus_address"));
                jcusphone.setText(rs.getString("cus_phone"));
                }
          String date="SELECT invoice_date FROM bills_RETAILS WHERE invoice_id="+invoice_id+";";       
          rs=stmt.executeQuery(date);
                if(rs.next()){
                Jinvoicedate.setText(rs.getString("invoice_date"));
                }
            
          DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
          int rows=model.getRowCount();
          
          String sqld="SELECT comp_name, product_name, length, width, height_MM, rate, quantity , total, discount_perc, net_amt FROM bills_RETAILS WHERE invoice_id="+invoice_id+";";      
          rs=stmt.executeQuery(sqld);
                if(rows>0)
                    {
                        for (int i=0;i<rows;i++)
                        {
                            model.removeRow(0);
                        }
                    }
                    while(rs.next())
                    {
                        model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
                    }
        } 
        catch (Exception e)
        {
           JOptionPane.showMessageDialog(this, e.getMessage());
        }          
          


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void JcusidbillFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JcusidbillFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_JcusidbillFocusGained

    private void JcusidbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcusidbillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcusidbillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFID;
    private javax.swing.JTextField Jcusidbill;
    private javax.swing.JTextField Jinvoicedate;
    private javax.swing.JTextField Jinvoicenumber;
    private javax.swing.JTextField Jinvoicenumberbill;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRbretails;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcombocompanyselect;
    private javax.swing.JComboBox jcomboproductselect;
    private javax.swing.JTextField jcusaddress;
    private javax.swing.JTextField jcusname;
    private javax.swing.JTextField jcusnamebill;
    private javax.swing.JTextField jcusnamebill2;
    private javax.swing.JTextField jcusphone;
    private javax.swing.JLabel jlbdis;
    private javax.swing.JLabel jlbtotal;
    private javax.swing.JRadioButton jrbwholesale;
    private javax.swing.JTextField jtfdis;
    private javax.swing.JTextField jtfheight;
    private javax.swing.JTextField jtflength;
    private javax.swing.JTextField jtfrate;
    private javax.swing.JTextField jtfwidth;
    // End of variables declaration//GEN-END:variables
}
