/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mahadevfoam_dealers;

import com.sun.crypto.provider.RSACipher;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.management.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class purchase_challan_input extends javax.swing.JFrame {

    /**
     * Creates new form purchase_challan_input
     */
    public purchase_challan_input() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jtfwidth = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfheight = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtflength = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcomboproductselect = new javax.swing.JComboBox();
        jcombocompanyselect = new javax.swing.JComboBox();
        jvendorname = new javax.swing.JTextField();
        jspinnerdate = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jinvoicenumberpur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtfvendor_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtpurchase = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfmrp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfquant = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jCombogodown = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jtfnetamt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtfupi = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setText("Height in MM");

        jLabel8.setText("Length in inches");

        jLabel9.setText("Width in inches");

        jLabel6.setText("Select company:-");

        jLabel7.setText("Select Size:-");

        jcomboproductselect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcomboproductselectFocusGained(evt);
            }
        });

        jcombocompanyselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombocompanyselectActionPerformed(evt);
            }
        });
        jcombocompanyselect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcombocompanyselectFocusGained(evt);
            }
        });

        jvendorname.setEditable(false);
        jvendorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvendornameActionPerformed(evt);
            }
        });
        jvendorname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jvendornameFocusGained(evt);
            }
        });

        jspinnerdate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1528298640000L), null, new java.util.Date(1528298640000L), java.util.Calendar.DAY_OF_MONTH));
        jspinnerdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jspinnerdate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspinnerdateStateChanged(evt);
            }
        });

        jLabel5.setText("Select Product:-");

        jLabel4.setText("Vendor Name:-");

        jLabel3.setText("Vendor Id:-");

        Jinvoicenumberpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JinvoicenumberpurActionPerformed(evt);
            }
        });
        Jinvoicenumberpur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JinvoicenumberpurFocusGained(evt);
            }
        });

        jLabel2.setText("Invoice Id:-");

        jButton1.setText("Open Vendor portal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Purchase Price:-");

        jtpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpurchaseActionPerformed(evt);
            }
        });
        jtpurchase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtpurchaseFocusGained(evt);
            }
        });

        jLabel11.setText("MRP:-");

        jtfmrp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfmrpFocusGained(evt);
            }
        });

        jLabel12.setText("UPI:-");

        jLabel13.setText("Invoice Date:-");

        jButton2.setText("Add To Stock");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Godown:-");

        jCombogodown.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCombogodownFocusGained(evt);
            }
        });

        jButton3.setText("Delete Item");

        jButton4.setText("View Invoice");

        jLabel15.setText("Quantity:-");

        jtfnetamt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfnetamtFocusGained(evt);
            }
        });

        jLabel16.setText("Net Value:-");

        jtfupi.setEditable(false);
        jtfupi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfupiActionPerformed(evt);
            }
        });
        jtfupi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfupiFocusGained(evt);
            }
        });

        jButton5.setText("Purchase log");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton6.setText("back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel12))
                                        .addGap(139, 139, 139)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtfquant, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtfnetamt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtfmrp, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtfupi, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtpurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(jtflength, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addGap(14, 14, 14)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jtfwidth, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jtfheight, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addComponent(jCombogodown, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jvendorname, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jcombocompanyselect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jcomboproductselect, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jtfvendor_id, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Jinvoicenumberpur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jspinnerdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1))))
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton6)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jspinnerdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jinvoicenumberpur, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfvendor_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jvendorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcombocompanyselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcomboproductselect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addGap(166, 166, 166))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtflength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfwidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtpurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfmrp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfquant, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfnetamt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfupi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombogodown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(38, 38, 38)
                .addComponent(jButton6)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboproductselectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcomboproductselectFocusGained
        try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
            Statement stmt = conn.createStatement();
            String company=jcombocompanyselect.getSelectedItem().toString();
            String companyid= "select cid from COMPANY_LIST where cname='"+company+"';";
            ResultSet rs=stmt.executeQuery(companyid);
            if(rs.next())
            {
                String c_id=rs.getString("cid");
                String PRODUCTLIST = "Select pname from product where cid='"+c_id+"';";
                ResultSet rs1 = stmt.executeQuery(PRODUCTLIST);
                jcomboproductselect.removeAllItems();
                while(rs1.next())
                {
                    jcomboproductselect.addItem(rs1.getString("Pname"));
                }
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jcomboproductselectFocusGained

    private void jcombocompanyselectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcombocompanyselectFocusGained
        try {
            Class.forName("java.sql.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
            Statement stmt = conn.createStatement();
            String combo_group = "Select DISTINCT cname from company_list";
            ResultSet rs = stmt.executeQuery(combo_group);

            jcombocompanyselect.removeAllItems();
            while(rs.next())
            {
                jcombocompanyselect.addItem(rs.getString("cname"));
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jcombocompanyselectFocusGained

    private void jvendornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvendornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jvendornameActionPerformed

    private void jvendornameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jvendornameFocusGained
        try {
             Class.forName("java.sql.Driver");
                    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
                    Statement stmt=conn.createStatement();
                    int id=Integer.parseInt(jtfvendor_id.getText());
                    String sql="select firm_name from vendor_details WHERE vendor_id='"+id+"';";
                    ResultSet rs1=stmt.executeQuery(sql);
                    
                    if(rs1.next())
                    {
                      jvendorname.setText(rs1.getString("firm_name"));
                    }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jvendornameFocusGained

    private void jspinnerdateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspinnerdateStateChanged
        //Spinner
        //Model property

        //jLabel1.setText(new SimpleDateFormat("yyyy-MM-dd").format(jSpinner1.getValue()));
        String date=(new SimpleDateFormat("yyyy-MM-dd").format(jspinnerdate.getValue()));
        // jcusname.setText(date); the value is stored in variable can be directly into database.
    }//GEN-LAST:event_jspinnerdateStateChanged

    private void JinvoicenumberpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JinvoicenumberpurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JinvoicenumberpurActionPerformed

    private void JinvoicenumberpurFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JinvoicenumberpurFocusGained
        
    }//GEN-LAST:event_JinvoicenumberpurFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new customer_management().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfupiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfupiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfupiActionPerformed

    private void jtpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpurchaseActionPerformed
      
    }//GEN-LAST:event_jtpurchaseActionPerformed

    private void jtpurchaseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtpurchaseFocusGained
          try 
        {
        Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        
        int length=Integer.parseInt(jtflength.getText());
        int width=Integer.parseInt(jtfwidth.getText());
        int height=Integer.parseInt(jtfheight.getText());
        long sq_inches_per_mm=length*width*height;
        
        String product=jcomboproductselect.getSelectedItem().toString();
        String price_from_db="select purchase_price_72_36 from product where pname='"+product+"';";
        ResultSet rs=stmt.executeQuery(price_from_db);
        
        if(rs.next())
        {
           int price=rs.getInt("purchase_price_72_36");
           long rate=(sq_inches_per_mm*price)/259200;
           jtpurchase.setText(rate+"");
        }
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jtpurchaseFocusGained

    private void jtfmrpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfmrpFocusGained
         try 
        {
        Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        
        int length=Integer.parseInt(jtflength.getText());
        int width=Integer.parseInt(jtfwidth.getText());
        int height=Integer.parseInt(jtfheight.getText());
        long sq_inches_per_mm=length*width*height;
        
        String product=jcomboproductselect.getSelectedItem().toString();
        String price_from_db="select price_72_36 from product where pname='"+product+"';";
        ResultSet rs=stmt.executeQuery(price_from_db);
        
        if(rs.next())
        {
           int price=rs.getInt("price_72_36");
           long rate=(sq_inches_per_mm*price)/259200;
           jtfmrp.setText(rate+"");
        }
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jtfmrpFocusGained

    private void jCombogodownFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCombogodownFocusGained
        try 
        {
         Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
        Statement stmt = conn.createStatement();
        String combo_group = "Select DISTINCT god_name from godown;";
        ResultSet rs = stmt.executeQuery(combo_group);

        
        while(rs.next())
        {
            jCombogodown.addItem(rs.getString(1));
        }   
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
                    }
    }//GEN-LAST:event_jCombogodownFocusGained

    private void jtfupiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfupiFocusGained
        try
        {
         Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement();
            
         
         String sqlinvoiceid="select ifnull(max(upi),'0') from stock;";
         ResultSet rs=stmt.executeQuery(sqlinvoiceid);
         if(rs.next()){
         String invoiceid=rs.getString("ifnull(max(upi),'0')");
         int maxinvoiceid=Integer.parseInt(invoiceid);
         int newinvoiceid=maxinvoiceid+1;
         jtfupi.setText(""+newinvoiceid);
         }   
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jtfupiFocusGained

    private void jtfnetamtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnetamtFocusGained
        int quant=Integer.parseInt(jtfquant.getText());
        int purchase=Integer.parseInt(jtpurchase.getText());
        int netamt=quant*purchase;
        jtfnetamt.setText(netamt+"");
    }//GEN-LAST:event_jtfnetamtFocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new office_management_menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try 
        {
          Class.forName("java.sql.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mahadev_foam","root","admin");
          Statement stmt = conn.createStatement();
          
          String date=(new SimpleDateFormat("yyyy-MM-dd").format(jspinnerdate.getValue()));
          String invoiceid=Jinvoicenumberpur.getText();
          String vendorid=jtfvendor_id.getText();
          String vendorname=jvendorname.getText();
          String company=jcombocompanyselect.getSelectedItem().toString();
          String product=jcomboproductselect.getSelectedItem().toString();
          String length=jtflength.getText();
          String height=jtfheight.getText();
          String width=jtfwidth.getText();
          String purch_price=jtpurchase.getText();
          String mrp=jtfmrp.getText();
          String quant=jtfquant.getText();
          String netamt=jtfnetamt.getText();
          String upi=jtfupi.getText();
          String godown=jCombogodown.getSelectedItem().toString();
          
          String insert_stock="insert into stock values('"+date+"','"+invoiceid+"',"
          + "'"+vendorid+"','"+vendorname+"','"+company+"','"+product+"','"+length+"','"+height+"','"+width+"','"+purch_price+"',"
          + "'"+mrp+"','"+quant+"','"+netamt+"','"+upi+"','"+godown+"')";
          stmt.executeUpdate(insert_stock);
          JOptionPane.showMessageDialog(this, "Item Added to Stock");
          
        }
        catch (Exception e)
        {
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jcombocompanyselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombocompanyselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombocompanyselectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase_challan_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase_challan_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase_challan_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase_challan_input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase_challan_input().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jinvoicenumberpur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jCombogodown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcombocompanyselect;
    private javax.swing.JComboBox jcomboproductselect;
    private javax.swing.JSpinner jspinnerdate;
    private javax.swing.JTextField jtfheight;
    private javax.swing.JTextField jtflength;
    private javax.swing.JTextField jtfmrp;
    private javax.swing.JTextField jtfnetamt;
    private javax.swing.JTextField jtfquant;
    private javax.swing.JTextField jtfupi;
    private javax.swing.JTextField jtfvendor_id;
    private javax.swing.JTextField jtfwidth;
    private javax.swing.JTextField jtpurchase;
    private javax.swing.JTextField jvendorname;
    // End of variables declaration//GEN-END:variables
}
